### ISSUE TITLE
python-tox and virtualenv can be dropped from Build-Depends

### ISSUE THREAD

**Issue by coreycb** [pythongssapi/debian-python-gssapi#3]
In ubuntu I've dropped python-tox and virtualenv from Build-Depends as they're not needed for package builds.  Would you mind doing the same?

**Comment by frozencemetery** [comment]
Not a problem.  I'll try to get a new version out in the next couple days.  Thanks for catching this!

**Comment by coreycb** [comment]
Thanks!
